---
- name: Create EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: us-east-2
    key_name: ansible-ec2-key
    instance_type: t2.micro
    image_id: ami-04f167a56786e4b09
    vpc_subnet_id: subnet-0f54d3d932601a661
    security_groups: ["sg-0ffc3795cd46f58d4"]
    tag_name: ansible-instance

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        wait: yes
        count: 1
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        security_groups: "{{ security_groups }}"
        tags:
          Name: "{{ tag_name }}"
        network:
          assign_public_ip: true
      register: ec2_result

    - name: Save public IP to file
      copy:
        dest: "./ec2_instance_ip.txt"
        content: "{{ ec2_result.instances[0].network_interfaces[0].association.public_ip }}"

    - name: Add new host to inventory (for next play)
      add_host:
        name: flask_ec2
        ansible_host: "{{ ec2_result.instances[0].network_interfaces[0].association.public_ip }}"
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ./ec2_key.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ ec2_result.instances[0].network_interfaces[0].association.public_ip }}"
        port: 22
        timeout: 300
        state: started

- name: Configure Flask app on EC2
  hosts: flask_ec2
  become: yes
  tasks:
    - name: Copy Flask app
      copy:
        src: flask_app.py
        dest: /home/ubuntu/flask_app.py
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Install Flask
      apt:
        name: python3-flask
        state: present
        update_cache: true

    - name: Run Flask app in background on port 8000
      become: false
      shell: |
        nohup python3 /home/ubuntu/flask_app.py > flask.log 2>&1 &
      args:
        executable: /bin/bash
