---
- name: Create EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: us-east-2
    key_name: ansible-ec2-key
    instance_type: t2.micro
    image_id: ami-04f167a56786e4b09
    vpc_subnet_id: subnet-0f54d3d932601a661
    security_groups: ["sg-0ffc3795cd46f58d4"]
    tag_name: ansible-instance


  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        wait: yes
        count: 1
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        security_groups: "{{ security_groups }}"
        tags:
          Name: "{{ tag_name }}"
        network:
          assign_public_ip: true
      register: ec2_result


    - name: Save public IP to file
      copy:
        dest: "./ec2_instance_ip.txt"
        content: "{{ ec2_result.instances[0].network_interfaces[0].association.public_ip }}"
      

    
  

    