name: Deploy EC2 with NGINX

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible and AWS collection
        run: |
          pip install ansible boto3
          ansible-galaxy collection install amazon.aws

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Run Ansible Playbook to launch EC2
        run: ansible-playbook main.yml

      - name: Read public IP from file
        id: get_ip
        run: |
          IP=$(cat ec2_instance_ip.txt)
          echo "INSTANCE_IP=$IP" >> $GITHUB_ENV


      - name: Save Private Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Wait for EC2 SSH to be ready
        run: |
          for i in {1..30}; do
            ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ env.INSTANCE_IP }} "echo connected" && break
            echo "Waiting for SSH..." && sleep 10
          done

      - name: Run Command on EC2 (NGINX check)
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@${{ env.INSTANCE_IP }} "sudo systemctl status nginx"
